apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodadvisor-frontend-deploy
  namespace: strapi-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: foodadvisor-frontend
  template:
    metadata:
      labels:
        app: foodadvisor-frontend
    spec:
      containers:
      - name: foodadvisor-frontend
        image: heraldofsolace/foodadvisor-client
        ports:
          - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: foodadvisor-frontend-svc
  namespace: strapi-prod
spec:
  selector:
    app: foodadvisor-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foodadvisor-frontend-ingress
  namespace: strapi-prod
spec:
  ingressClassName: nginx
  rules:
    - host: foodadvisor.client.aide1.fr
      http:
        paths:
          - backend:
              service:
                name: foodadvisor-frontend-svc
                port:
                  number: 3000
            path: /
            pathType: Prefix
