apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodadvisor-backend-deploy
  namespace: strapi-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: foodadvisor-backend
  template:
    metadata:
      labels:
        app: foodadvisor-backend
    spec:
      containers:
      - name: foodadvisor-backend
        image: heraldofsolace/foodadvisor-api
        ports:
          - containerPort: 1337

---

apiVersion: v1
kind: Service
metadata:
  name: foodadvisor-backend-svc
  namespace: strapi-prod
spec:
  selector:
    app: foodadvisor-backend
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foodadvisor-backend-ingress
  namespace: strapi-prod
spec:
  ingressClassName: nginx
  rules:
    - host: foodadvisor.backend.aide1.fr
      http:
        paths:
          - backend:
              service:
                name: foodadvisor-backend-svc
                port:
                  number: 1337
            path: /
            pathType: Prefix
      
